// Code generated by go-swagger; DO NOT EDIT.

// Package server WeatherStat Explorer API
//
//	API for WeatherStat explorer service
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api/explorer
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package server
