// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteCitiesHandlerFunc turns a function with the right signature into a delete cities handler
type DeleteCitiesHandlerFunc func(DeleteCitiesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCitiesHandlerFunc) Handle(params DeleteCitiesParams) middleware.Responder {
	return fn(params)
}

// DeleteCitiesHandler interface for that can handle valid delete cities params
type DeleteCitiesHandler interface {
	Handle(DeleteCitiesParams) middleware.Responder
}

// NewDeleteCities creates a new http.Handler for the delete cities operation
func NewDeleteCities(ctx *middleware.Context, handler DeleteCitiesHandler) *DeleteCities {
	return &DeleteCities{Context: ctx, Handler: handler}
}

/*
	DeleteCities swagger:route DELETE /cities deleteCities

Deletes city from subscription list
*/
type DeleteCities struct {
	Context *middleware.Context
	Handler DeleteCitiesHandler
}

func (o *DeleteCities) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteCitiesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
