// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTempHandlerFunc turns a function with the right signature into a get temp handler
type GetTempHandlerFunc func(GetTempParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTempHandlerFunc) Handle(params GetTempParams) middleware.Responder {
	return fn(params)
}

// GetTempHandler interface for that can handle valid get temp params
type GetTempHandler interface {
	Handle(GetTempParams) middleware.Responder
}

// NewGetTemp creates a new http.Handler for the get temp operation
func NewGetTemp(ctx *middleware.Context, handler GetTempHandler) *GetTemp {
	return &GetTemp{Context: ctx, Handler: handler}
}

/*
	GetTemp swagger:route GET /temp getTemp

Returns an average temp for archive period
*/
type GetTemp struct {
	Context *middleware.Context
	Handler GetTempHandler
}

func (o *GetTemp) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTempParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
