// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MiyukiMori11/weatherstat/explorer/internal/models"
)

// GetTempOKCode is the HTTP code returned for type GetTempOK
const GetTempOKCode int = 200

/*
GetTempOK OK

swagger:response getTempOK
*/
type GetTempOK struct {

	/*
	  In: Body
	*/
	Payload *models.CityTemp `json:"body,omitempty"`
}

// NewGetTempOK creates GetTempOK with default headers values
func NewGetTempOK() *GetTempOK {

	return &GetTempOK{}
}

// WithPayload adds the payload to the get temp o k response
func (o *GetTempOK) WithPayload(payload *models.CityTemp) *GetTempOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get temp o k response
func (o *GetTempOK) SetPayload(payload *models.CityTemp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTempOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTempBadRequestCode is the HTTP code returned for type GetTempBadRequest
const GetTempBadRequestCode int = 400

/*
GetTempBadRequest Bad request

swagger:response getTempBadRequest
*/
type GetTempBadRequest struct {
}

// NewGetTempBadRequest creates GetTempBadRequest with default headers values
func NewGetTempBadRequest() *GetTempBadRequest {

	return &GetTempBadRequest{}
}

// WriteResponse to the client
func (o *GetTempBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetTempNotFoundCode is the HTTP code returned for type GetTempNotFound
const GetTempNotFoundCode int = 404

/*
GetTempNotFound City not found

swagger:response getTempNotFound
*/
type GetTempNotFound struct {
}

// NewGetTempNotFound creates GetTempNotFound with default headers values
func NewGetTempNotFound() *GetTempNotFound {

	return &GetTempNotFound{}
}

// WriteResponse to the client
func (o *GetTempNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetTempInternalServerErrorCode is the HTTP code returned for type GetTempInternalServerError
const GetTempInternalServerErrorCode int = 500

/*
GetTempInternalServerError Server error

swagger:response getTempInternalServerError
*/
type GetTempInternalServerError struct {
}

// NewGetTempInternalServerError creates GetTempInternalServerError with default headers values
func NewGetTempInternalServerError() *GetTempInternalServerError {

	return &GetTempInternalServerError{}
}

// WriteResponse to the client
func (o *GetTempInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
