// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MiyukiMori11/weatherstat/explorer/internal/models"
)

// GetCitiesOKCode is the HTTP code returned for type GetCitiesOK
const GetCitiesOKCode int = 200

/*
GetCitiesOK OK

swagger:response getCitiesOK
*/
type GetCitiesOK struct {

	/*
	  In: Body
	*/
	Payload *models.CitiesStat `json:"body,omitempty"`
}

// NewGetCitiesOK creates GetCitiesOK with default headers values
func NewGetCitiesOK() *GetCitiesOK {

	return &GetCitiesOK{}
}

// WithPayload adds the payload to the get cities o k response
func (o *GetCitiesOK) WithPayload(payload *models.CitiesStat) *GetCitiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cities o k response
func (o *GetCitiesOK) SetPayload(payload *models.CitiesStat) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCitiesBadRequestCode is the HTTP code returned for type GetCitiesBadRequest
const GetCitiesBadRequestCode int = 400

/*
GetCitiesBadRequest Bad request

swagger:response getCitiesBadRequest
*/
type GetCitiesBadRequest struct {
}

// NewGetCitiesBadRequest creates GetCitiesBadRequest with default headers values
func NewGetCitiesBadRequest() *GetCitiesBadRequest {

	return &GetCitiesBadRequest{}
}

// WriteResponse to the client
func (o *GetCitiesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetCitiesNotFoundCode is the HTTP code returned for type GetCitiesNotFound
const GetCitiesNotFoundCode int = 404

/*
GetCitiesNotFound Not found

swagger:response getCitiesNotFound
*/
type GetCitiesNotFound struct {
}

// NewGetCitiesNotFound creates GetCitiesNotFound with default headers values
func NewGetCitiesNotFound() *GetCitiesNotFound {

	return &GetCitiesNotFound{}
}

// WriteResponse to the client
func (o *GetCitiesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetCitiesInternalServerErrorCode is the HTTP code returned for type GetCitiesInternalServerError
const GetCitiesInternalServerErrorCode int = 500

/*
GetCitiesInternalServerError Server error

swagger:response getCitiesInternalServerError
*/
type GetCitiesInternalServerError struct {
}

// NewGetCitiesInternalServerError creates GetCitiesInternalServerError with default headers values
func NewGetCitiesInternalServerError() *GetCitiesInternalServerError {

	return &GetCitiesInternalServerError{}
}

// WriteResponse to the client
func (o *GetCitiesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
