// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MiyukiMori11/weatherstat/explorer/internal/models"
)

// PostCitiesOKCode is the HTTP code returned for type PostCitiesOK
const PostCitiesOKCode int = 200

/*
PostCitiesOK OK

swagger:response postCitiesOK
*/
type PostCitiesOK struct {

	/*
	  In: Body
	*/
	Payload *models.CityTemp `json:"body,omitempty"`
}

// NewPostCitiesOK creates PostCitiesOK with default headers values
func NewPostCitiesOK() *PostCitiesOK {

	return &PostCitiesOK{}
}

// WithPayload adds the payload to the post cities o k response
func (o *PostCitiesOK) WithPayload(payload *models.CityTemp) *PostCitiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post cities o k response
func (o *PostCitiesOK) SetPayload(payload *models.CityTemp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostCitiesBadRequestCode is the HTTP code returned for type PostCitiesBadRequest
const PostCitiesBadRequestCode int = 400

/*
PostCitiesBadRequest Bad request

swagger:response postCitiesBadRequest
*/
type PostCitiesBadRequest struct {
}

// NewPostCitiesBadRequest creates PostCitiesBadRequest with default headers values
func NewPostCitiesBadRequest() *PostCitiesBadRequest {

	return &PostCitiesBadRequest{}
}

// WriteResponse to the client
func (o *PostCitiesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostCitiesNotFoundCode is the HTTP code returned for type PostCitiesNotFound
const PostCitiesNotFoundCode int = 404

/*
PostCitiesNotFound City not found

swagger:response postCitiesNotFound
*/
type PostCitiesNotFound struct {
}

// NewPostCitiesNotFound creates PostCitiesNotFound with default headers values
func NewPostCitiesNotFound() *PostCitiesNotFound {

	return &PostCitiesNotFound{}
}

// WriteResponse to the client
func (o *PostCitiesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PostCitiesInternalServerErrorCode is the HTTP code returned for type PostCitiesInternalServerError
const PostCitiesInternalServerErrorCode int = 500

/*
PostCitiesInternalServerError Server error

swagger:response postCitiesInternalServerError
*/
type PostCitiesInternalServerError struct {
}

// NewPostCitiesInternalServerError creates PostCitiesInternalServerError with default headers values
func NewPostCitiesInternalServerError() *PostCitiesInternalServerError {

	return &PostCitiesInternalServerError{}
}

// WriteResponse to the client
func (o *PostCitiesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
