// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CitiesStat cities stat
//
// swagger:model CitiesStat
type CitiesStat struct {

	// Number of cities in the subscription
	// Minimum: 0
	CitiesCount *int64 `json:"cities_count,omitempty"`

	// List of cities in the subscription
	CityNames []string `json:"city_names"`
}

// Validate validates this cities stat
func (m *CitiesStat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCitiesCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CitiesStat) validateCitiesCount(formats strfmt.Registry) error {
	if swag.IsZero(m.CitiesCount) { // not required
		return nil
	}

	if err := validate.MinimumInt("cities_count", "body", *m.CitiesCount, 0, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this cities stat based on context it is used
func (m *CitiesStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CitiesStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CitiesStat) UnmarshalBinary(b []byte) error {
	var res CitiesStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
