// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CitiesStat cities stat
//
// swagger:model CitiesStat
type CitiesStat struct {

	// List of cities in the subscription
	Cities []*CityInfo `json:"cities"`

	// Number of cities in the subscription
	// Minimum: 0
	CitiesCount *int64 `json:"cities_count,omitempty"`
}

// Validate validates this cities stat
func (m *CitiesStat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCities(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCitiesCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CitiesStat) validateCities(formats strfmt.Registry) error {
	if swag.IsZero(m.Cities) { // not required
		return nil
	}

	for i := 0; i < len(m.Cities); i++ {
		if swag.IsZero(m.Cities[i]) { // not required
			continue
		}

		if m.Cities[i] != nil {
			if err := m.Cities[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cities" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cities" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CitiesStat) validateCitiesCount(formats strfmt.Registry) error {
	if swag.IsZero(m.CitiesCount) { // not required
		return nil
	}

	if err := validate.MinimumInt("cities_count", "body", *m.CitiesCount, 0, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this cities stat based on the context it is used
func (m *CitiesStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCities(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CitiesStat) contextValidateCities(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Cities); i++ {

		if m.Cities[i] != nil {
			if err := m.Cities[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cities" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cities" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CitiesStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CitiesStat) UnmarshalBinary(b []byte) error {
	var res CitiesStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
