// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CityTemp city temp
//
// swagger:model CityTemp
type CityTemp struct {

	// Average temperature in Celsius
	Avgc float64 `json:"avg_c,omitempty"`

	// Average temperature in Fahrenheit
	Avgf float64 `json:"avg_f,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this city temp
func (m *CityTemp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this city temp based on context it is used
func (m *CityTemp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CityTemp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CityTemp) UnmarshalBinary(b []byte) error {
	var res CityTemp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
