gateway:
  services:
    - name: "explorer"
      root: /api/explorer
      host: '172.33.3.1'
      port: "8181"
      scheme: HTTP
      healthPath: /health
      routes:
        - path: /cities
          method: POST
        - path: /cities
          method: DELETE
        - path: /cities
          method: GET
        - path: /temp
          method: GET
server:
  listenHost: "0.0.0.0"
  listenPort: "8080"
  scheme: HTTP
  shutdownTimeoutSec: 5