swagger: "2.0"
info:
  title: WeatherStat Explorer API
  description: API for WeatherStat explorer service
  version: 1.0.0
basePath: /api/explorer
schemes:
  - http

paths:
  /cities:
    get:
      summary: Returns a cities stat.

      produces:
        - application/json
      responses:
        200:
          description: OK
          schema: 
            $ref: '#/definitions/CitiesStat'
        400:
          description: Bad request
        404:
          description: Not found
        500:
          description: Server error
    post:
      summary: Adds a new city into subscripton list

      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/CityNameBody'
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema: 
            $ref: '#/definitions/CityTemp'
        400:
          description: Bad request
        404:
          description: City not found
        500:
          description: Server error
    delete:
      summary: Deletes city from subscription list

      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/CityNameQuery'
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema: 
            $ref: '#/definitions/CitiesStat'
        400:
          description: Bad request
        404:
          description: Not found
        500:
          description: Server error
  /temp:
    get:
      summary: Returns an average temp for archive period

      parameters:
        - $ref: '#/parameters/CityNameQuery'
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema: 
            $ref: '#/definitions/CityTemp'
        400:
          description: Bad request
        404:
          description: City not found
        500:
          description: Server error

parameters:
  CityNameQuery:
    in: query
    name: city_name
    type: string
    required: true
    maxLength: 25
    pattern: ^[\w\-\' ]+ 
  CountryNameQuery:
    in: query
    name: country_name
    type: string
    required: true
    maxLength: 25
    pattern: ^[\w\-\' ]+ 
  CityNameBody:
    in: body
    name: city_name
    required: true
    schema: 
      $ref: '#/definitions/CityName'
  CountryNameBody:
    in: body
    name: country_name
    required: true
    schema: 
      $ref: '#/definitions/CountryName'


definitions:
  CityTemp:
    type: object
    properties: 
      name:
        type: string
      avg_c:
        description: Average temperature in Celsius
        type: integer
      avg_f:
        description: Average temperature in Fahrenheit
        type: integer
  CitiesStat:
    type: object
    properties: 
      cities_count:
        description: Number of cities in the subscription
        type: integer
        minimum: 0
      city_names:
        description: List of cities in the subscription
        type: array
        items: {
          type: string
        }
  CityName:
    type: string
    maxLength: 25
    pattern: ^[\w\-\' ]+
  CountryName:
    type: string
    maxLength: 25
    pattern: ^[\w\-\' ]+
